import type { CandidateStatus, TrackerStage } from "@/lib/types";

/** One candidate mapped into the funnel shape — the extraction seam for a future standalone export. */
export interface FunnelCandidate {
  screeningId: number;
  candidateName: string;
  projectId: number | null;
  projectName: string;
  recruiterId: string | null;
  recruiterEmail: string | null;
  /**
   * "outbound" = LinkedIn-sourced (linkedin_mode), "agency" = came in via an
   * agency (agency_name set), "referred" = referred by a person
   * (referrer_name set), "inbound" = ordinary applicant, the default. Kept
   * as this inbound/outbound/agency/referred naming rather than switching to
   * lib/sourceType.ts's applicant/linkedin/agency/referred strings, to
   * minimize churn across this file's many existing
   * `c.source === "outbound"` call sites — same four-way classification
   * underneath (see getSourceType()). Agency added 2026-07-20, referred
   * added 2026-08-26, both Vlad's ask.
   */
  source: "inbound" | "outbound" | "agency" | "referred";
  /** Set only when source === "agency". */
  agencyName?: string | null;
  /** Set only when source === "referred". */
  referrerName?: string | null;
  score: number;
  /** True if this score cleared the candidate's own project's score_threshold (defaults to 45 if the project has none set, or no project at all) — independent of current status, so a candidate manually archived later for an unrelated reason still counts as having passed. */
  passedThreshold: boolean;
  status: CandidateStatus;
  previousStatus: CandidateStatus | null;
  trackerStage: TrackerStage | null;
  previousTrackerStage: TrackerStage | null;
  /** Furthest tracker stage reached, even if since rejected — falls back to trackerStage, then previousTrackerStage if the current stage is Reject. */
  furthestStage: TrackerStage | null;
  /** True if either Feature 1.1 (same-project duplicate) or 1.4 (cross-project history alert) has flagged this candidate. */
  hasFraudFlag: boolean;
  createdAt: string;
  /**
   * Current employer/title, 2026-08-04 (Vlad's ask: FunnelView Excel export
   * "Current Company" / "Current Title" columns). Null until backfilled —
   * see supabase-migration-current-role.sql and the "Regenerate
   * trajectories" button in a project's Settings tab.
   */
  currentCompany: string | null;
  currentTitle: string | null;
  /**
   * "Total experience" export column — 1 sentence preferred, 2 sentences
   * absolute max, facts-only (total years, domain, seniority), generated by
   * lib/generateTrajectory.ts as its OWN dedicated field, deliberately NOT
   * derived from the (much longer) careerTrajectory narrative — Vlad asked
   * for this to be short enough to trust at a glance, 2026-08-04. Null for
   * any screening from before 2026-08-06 (when this started populating
   * automatically at scoring time) — the "Regenerate trajectories" backfill
   * button that used to fix this for older candidates was removed
   * 2026-08-15 (Vlad's call: no longer needed) — a pre-08-06 screening
   * missing this field now stays null permanently unless re-screened.
   */
  totalExperienceSummary: string | null;
  /**
   * "Signals" export column, 2026-08-15 (Vlad's ask) — replaces "Total
   * experience" (totalExperienceSummary above, which stays as a field but
   * is no longer used in the export). Strongest strength + weakest concern,
   * both already generated on every screening, no new AI call. Null
   * whenever the candidate genuinely has zero strengths/concerns listed —
   * expected for very sparse profiles, not a sign of a missing backfill.
   */
  topStrength: string | null;
  topConcern: string | null;
  /**
   * "LinkedIn" export column, 2026-08-06 (Vlad's ask). Auto-extracted from
   * the resume's own contact info — genuinely absent for many candidates
   * whose resume never lists one, which is expected, not a sign of a
   * missing backfill (unlike currentCompany/currentTitle/
   * totalExperienceSummary above — see that field's own comment for why a
   * pre-2026-08-06 screening can be permanently null here now that the
   * backfill button is gone).
   */
  linkedinUrl: string | null;
}

export interface FunnelStageCount {
  key: string;
  label: string;
  count: number;
  /** Percentage of the immediately preceding stage's count. Null for the first stage. */
  conversionFromPrevious: number | null;
  /**
   * Same stage, split by source — added 2026-07-27 (Vlad's ask: "combine
   * sourced/applied/agency [into] the main funnel... so it's easier to track
   * stages for those sources with the main funnel stages"). Always sums to
   * exactly `count`, since it's computed by re-running the same stage
   * predicate against each source's own candidate subset (see
   * lib/funnelview/data.ts's computeStages). Replaces the old standalone
   * "Sourced vs. Applied" section, which only ever showed one blended total
   * with no per-stage breakdown.
   */
  bySource: FunnelSourceSplit;
}

export interface FunnelSourceSplit {
  inbound: number;
  outbound: number;
  agency: number;
  /** Added 2026-08-26 (Vlad's ask) — exact mirror of agency's slot. */
  referred: number;
}

/** Same funnel shape as FunnelData's top-level stages, scoped to one project instead of blended across all of them. */
export interface FunnelProjectBreakdown {
  projectId: number;
  projectName: string;
  totalScreened: number;
  stages: FunnelStageCount[];
  archivedOrRejected: number;
}

export interface FunnelData {
  totalScreened: number;
  stages: FunnelStageCount[];
  sourceSplit: FunnelSourceSplit;
  archivedOrRejected: number;
  candidates: FunnelCandidate[];
  /** Per-project breakdown of the same funnel, sorted by totalScreened descending. Candidates with no assigned project are excluded (already reflected in the blended totals above). */
  byProject: FunnelProjectBreakdown[];
}
