-- Interview View migration
-- Run this in your Supabase SQL editor

-- 1. Interview questions (generated by Claude, cached per candidate)
ALTER TABLE screenings ADD COLUMN IF NOT EXISTS interview_questions text[];

-- 2. LinkedIn PDF path in Supabase Storage (stored when credibility check is run)
ALTER TABLE screenings ADD COLUMN IF NOT EXISTS linkedin_pdf_path text;

-- 3. Candidate photo (safety — may already exist from a prior session)
ALTER TABLE screenings ADD COLUMN IF NOT EXISTS photo_url text;
